export const featuredMenu = [
    {
        itemName: 'All in one Pack (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: 'Free Course',
        image: '/assets/images/featured/all-in-one.png',
        id: 1725362245619,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details: ["FREE Mix Veg  with Fried Potato Course", "100% veg recipes", "Step-by-step cooking video instructions + Detailed PDF notes", "Doubt solving over call", "Learn from Experts", "Explore new recipes every day", "2,00,00+ Trained students", "Free Lifetime Access"]
    },
    {
        itemName: 'Variety of Juice (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: '',
        image: '/assets/images/featured/juice.png',
        id: 1725238224581,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details: ["FREE Mix Veg  with Fried Potato Course", "100% veg recipes", "Step-by-step cooking video instructions + Detailed PDF notes", "Doubt solving over call", "Learn from Experts", "Explore new recipes every day", "2,00,00+ Trained students", "Free Lifetime Access"]
    },
    {
        itemName: 'Variety of pork bar (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: 'Certified Course',
        image: '/assets/images/featured/pork-bar.jpg',
        id: 1725469224523,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details: ["FREE Mix Veg  with Fried Potato Course", "100% veg recipes", "Step-by-step cooking video instructions + Detailed PDF notes", "Doubt solving over call", "Learn from Experts", "Explore new recipes every day", "2,00,00+ Trained students", "Free Lifetime Access"]
    },
    {
        itemName: 'Noodles with Veggies (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: '',
        image: '/assets/images/featured/noodles.jpg',
        id: 1725441224518,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details: ["FREE Mix Veg  with Fried Potato Course", "100% veg recipes", "Step-by-step cooking video instructions + Detailed PDF notes", "Doubt solving over call", "Learn from Experts", "Explore new recipes every day", "2,00,00+ Trained students", "Free Lifetime Access"]
    },
    {
        itemName: 'Pan Cake with banana (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: 'Certified Course',
        image: '/assets/images/featured/pan-cake.jpg',
        id: 1725441224507,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details: ["FREE Mix Veg  with Fried Potato Course", "100% veg recipes", "Step-by-step cooking video instructions + Detailed PDF notes", "Doubt solving over call", "Learn from Experts", "Explore new recipes every day", "2,00,00+ Trained students", "Free Lifetime Access"]
    },
    {
        itemName: 'Variety of mix nuts (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: '',
        image: '/assets/images/featured/mix-nuts.jpg',
        id: 1725441222148,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details: ["FREE Mix Veg  with Fried Potato Course", "100% veg recipes", "Step-by-step cooking video instructions + Detailed PDF notes", "Doubt solving over call", "Learn from Experts", "Explore new recipes every day", "2,00,00+ Trained students", "Free Lifetime Access"]
    },
]