export const freeRecipesMenu = [
    {
        itemName: 'All in one Pack (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: 'Free Course',
        image: '/assets/images/featured/all-in-one.png',
        id: 9999362245619,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details:["FREE Mix Veg  with Fried Potato Course","100% veg recipes","Step-by-step cooking video instructions + Detailed PDF notes","Doubt solving over call","Learn from Experts","Explore new recipes every day","2,00,00+ Trained students","Free Lifetime Access"]
    },
    {
        itemName: 'Variety of Juice (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: '',
        image: '/assets/images/featured/juice.png',
        id: 1725362249999,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details:["FREE Mix Veg  with Fried Potato Course","100% veg recipes","Step-by-step cooking video instructions + Detailed PDF notes","Doubt solving over call","Learn from Experts","Explore new recipes every day","2,00,00+ Trained students","Free Lifetime Access"]
    },
    {
        itemName: 'Variety of pork bar (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: 'Free Course',
        image: '/assets/images/featured/pork-bar.jpg',
        id: 1725399995619,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details:["FREE Mix Veg  with Fried Potato Course","100% veg recipes","Step-by-step cooking video instructions + Detailed PDF notes","Doubt solving over call","Learn from Experts","Explore new recipes every day","2,00,00+ Trained students","Free Lifetime Access"]
    },
]

export const freeCourseRecipesMenu = [
    {
        itemName: 'All in one Pack (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: 'Free Course',
        image: '/assets/images/featured/all-in-one.png',
        id: 9999362245619,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details:["FREE Mix Veg  with Fried Potato Course","100% veg recipes","Step-by-step cooking video instructions + Detailed PDF notes","Doubt solving over call","Learn from Experts","Explore new recipes every day","2,00,00+ Trained students","Free Lifetime Access"]
    },
    {
        itemName: 'Variety of Juice (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: '',
        image: '/assets/images/featured/juice.png',
        id: 1725362249999,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details:["FREE Mix Veg  with Fried Potato Course","100% veg recipes","Step-by-step cooking video instructions + Detailed PDF notes","Doubt solving over call","Learn from Experts","Explore new recipes every day","2,00,00+ Trained students","Free Lifetime Access"]
    },
    {
        itemName: 'Variety of pork bar (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: 'Free Course',
        image: '/assets/images/featured/pork-bar.jpg',
        id: 1725399995619,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details:["FREE Mix Veg  with Fried Potato Course","100% veg recipes","Step-by-step cooking video instructions + Detailed PDF notes","Doubt solving over call","Learn from Experts","Explore new recipes every day","2,00,00+ Trained students","Free Lifetime Access"]
    },
    {
        itemName: 'All in one Pack (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: 'Free Course',
        image: '/assets/images/featured/all-in-one.png',
        id: 9999362245619,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details:["FREE Mix Veg  with Fried Potato Course","100% veg recipes","Step-by-step cooking video instructions + Detailed PDF notes","Doubt solving over call","Learn from Experts","Explore new recipes every day","2,00,00+ Trained students","Free Lifetime Access"]
    },
    {
        itemName: 'Variety of Juice (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: '',
        image: '/assets/images/featured/juice.png',
        id: 1725362249999,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details:["FREE Mix Veg  with Fried Potato Course","100% veg recipes","Step-by-step cooking video instructions + Detailed PDF notes","Doubt solving over call","Learn from Experts","Explore new recipes every day","2,00,00+ Trained students","Free Lifetime Access"]
    },
    {
        itemName: 'Variety of pork bar (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: 'Free Course',
        image: '/assets/images/featured/pork-bar.jpg',
        id: 1725399995619,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details:["FREE Mix Veg  with Fried Potato Course","100% veg recipes","Step-by-step cooking video instructions + Detailed PDF notes","Doubt solving over call","Learn from Experts","Explore new recipes every day","2,00,00+ Trained students","Free Lifetime Access"]
    },
]