export const healthyTastyRecipesMenu = [
    {
        itemName: 'Variety of rice jeera (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: 'Free Course',
        image: '/assets/images/healthy-and-tasty/jeera-rice.png',
        id: 1725332245619,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details: ["FREE Mix Veg  with Fried Potato Course", "100% veg recipes", "Step-by-step cooking video instructions + Detailed PDF notes", "Doubt solving over call", "Learn from Experts", "Explore new recipes every day", "2,00,00+ Trained students", "Free Lifetime Access"]
    },
    {
        itemName: 'Healthy salad (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: '',
        image: '/assets/images/healthy-and-tasty/salad.png',
        id: 1725222245619,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details: ["FREE Mix Veg  with Fried Potato Course", "100% veg recipes", "Step-by-step cooking video instructions + Detailed PDF notes", "Doubt solving over call", "Learn from Experts", "Explore new recipes every day", "2,00,00+ Trained students", "Free Lifetime Access"]
    },
    {
        itemName: 'Soup and curry (Lifetime Access)',
        rating: '4.2',
        ratingPerson: 2002,
        currentPrice: 500,
        price: 5000,
        course: 'Certified Course',
        image: '/assets/images/healthy-and-tasty/soup-and-curry.png',
        id: 1778782245619,
        enrolledDetail: {
            coursePrice: '$420.38',
            instructor: 'Zibiah Surya',
            lectures: 10,
            level: 'Begginer',
            language: "English",
            certificate: 'Yes',
            duration: "05 hr 15 mins",
        },
        by: 'Zibiah Surya',
        enrolledStudents: 300,
        details: ["FREE Mix Veg  with Fried Potato Course", "100% veg recipes", "Step-by-step cooking video instructions + Detailed PDF notes", "Doubt solving over call", "Learn from Experts", "Explore new recipes every day", "2,00,00+ Trained students", "Free Lifetime Access"]
    },
]